- name: ":lady_beetle: bug"
  color: "d73a4a"
  description: "Something isn't working"
  from_name: "bug"
- name: ":blue_book: documentation"
  color: 0075ca
  description: "Improvements or additions to documentation"
  from_name: "documentation"
- name: ":family: duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"
  from_name: "duplicate"
- name: ":fire: enhancement"
  color: "a2eeef"
  description: "New feature or request"
  from_name: "enhancement"
- name: ":pray: help wanted"
  color: "008672"
  description: "Extra attention is needed"
  from_name: ":raised_hand: help wanted"
- name: ":hatching_chick: good first issue"
  color: "7057ff"
  description: "Good for newcomers"
  from_name: ":raised_hand: good first issue"
- name: ":x: invalid"
  color: "e4e669"
  description: "This doesn't seem right"
  from_name: "invalid"
- name: ":grey_question: question"
  color: "d876e3"
  description: "Further information is requested"
  from_name: "question"
- name: ":lock: wontfix"
  color: "ffffff"
  description: "This will not be worked on"
  from_name: "wontfix"
- name: ":rocket: feature"
  color: "ccf5ff"
  description: "This adds some form of new functionality"
  from_name: "feature"
- name: ":boom: breaking change"
  color: "efa7ae"
  description: "This breaks existing behavior"
  from_name: "breaking change"
- name: ":sparkles: mysterious"
  color: "cccccc"
  description: "We forgot to label this"
  from_name: "mysterious"
- name: ":hammer: chore"
  color: "27127c"
  description: "Just keeping things neat and tidy"
  from_name: "chore"
- name: ":package: dependencies"
  color: "edc397"
  description: "Pull requests that update a dependency file"
  from_name: "dependencies"
- name: ":shipit: merge"
  color: "98ed98"
  description: "Shipit!"
  from_name: "merge"
- name: ":construction: deprecated"
  color: "dd824d"
  description: "Deprecated functionality"
  from_name: "deprecated"
- name: ":wastebasket: removed"
  color: "fce99f"
  description: "Removed functionality"
  from_name: "removed"
- name: ":old_key: security"
  color: "cbce1e"
  description: "Security related issue"
  from_name: "security"
- name: ':truck: private-dependencies'
  color: "edc397"
  description: "Private dependency"
  from_name: "private-dependencies"
- name: ':trident: rebase'
  color: "ffcc66"
  description: "Rebase branch"
- name: ':vertical_traffic_light: stop updating'
  color: "800000"
  description: "Stop Updating"
- name: ':stop_sign: blocked'
  color: "FF5600"
  description: "Issue is blocked waiting for something or someone"