name: sync-labels
on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          yaml-file: .github/labels.yml
          skip-delete: false
          dry-run: false
          github-token: ${{ secrets.GITHUB_TOKEN }}