name: self-host-test
on:
  push:
    branches:
      - master
  workflow_call:
  workflow_dispatch:

jobs:
  self-host-test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: test
        run: echo "Test"